# -*- coding: utf-8 -*-
import os.path

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QVBoxLayout,QDialog,QPushButton,QLabel,QLineEdit,QMessageBox,QTextEdit,QHBoxLayout
import sys
import os
import xml.etree.ElementTree as ET
from PyQt5.QtCore import Qt, pyqtSignal

BASE_DIR = os.path.dirname(os.path.realpath(sys.argv[0]))
class Ui_ThresholdWindow(QDialog):

    Signal_OneParameter = pyqtSignal(int,int,int)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.filed_dict = {}
        self.init_ui()

    def init_ui(self):
        """
        初始化对话框
        :return:
        """
        self.setWindowTitle("ThresholdSetting")
        self.resize(300,200)
        layout = QVBoxLayout()
        #读取文件中的标志
        lbl = QLabel()
        lbl.setText('标志:')
        layout.addWidget(lbl)
        self.com_box = QtWidgets.QComboBox()
        self.threshold_flag = {}
        file_xml = ET.parse(os.path.join(BASE_DIR,'db',"Threshold.xml"))
        if file_xml:
            data_list = list(file_xml.getroot())
        for data in data_list:
            strN = str(data.get('Name'))
            self.com_box.addItem(strN)
            self.threshold_flag[strN] = int(data.get('Index'))
        layout.addWidget(self.com_box)

        #添加标签
        lab_layout = QHBoxLayout()
        lbl = QLabel()
        lbl.setText('阈值:')
        lab_layout.addWidget(lbl)
        lab_layout.addStretch()
        #添加数值显示标签
        self.valshow = QLabel()
        self.valshow.setText('0')
        lab_layout.addWidget(self.valshow)
        layout.addLayout(lab_layout)

        self.tb_thresholdVal = QtWidgets.QSlider(Qt.Horizontal)
        self.tb_thresholdVal.setGeometry(QtCore.QRect(60,60,241,22))
        self.tb_thresholdVal.setMinimum(0)
        self.tb_thresholdVal.setMaximum(255)
        self.tb_thresholdVal.setValue(128)
        self.tb_thresholdVal.setSingleStep(1)
        self.tb_thresholdVal.valueChanged.connect(self.thresholdvalchange)
        #tb_threshold.setOrientation(Qt.Horizontal)
        layout.addWidget(self.tb_thresholdVal)

        #添加标签
        max_layout = QHBoxLayout()
        lbl = QLabel()
        lbl.setText('最大值:')
        max_layout.addWidget(lbl)
        max_layout.addStretch()
        # 添加数值显示标签
        self.maxshow = QLabel('255')
        max_layout.addWidget(self.maxshow)
        layout.addLayout(max_layout)

        self.tb_thresholdMax = QtWidgets.QSlider(Qt.Horizontal)
        self.tb_thresholdMax.setGeometry(QtCore.QRect(60,60,241,22))
        self.tb_thresholdMax.setMinimum(0)
        self.tb_thresholdMax.setMaximum(255)
        self.tb_thresholdMax.setValue(255)
        self.tb_thresholdMax.setSingleStep(1)
        self.tb_thresholdMax.valueChanged.connect(self.thresholdvalchange)
        #tb_threshold.setOrientation(Qt.Horizontal)
        layout.addWidget(self.tb_thresholdMax)

        btn_ok = QPushButton()
        self.tb_thresholdMax.setOrientation(Qt.Horizontal)
        layout.addWidget(self.tb_thresholdMax)
        self.setLayout(layout)
        print('{}{}'.format(self.tb_thresholdVal.value(),self.tb_thresholdMax.value()))
    def thresholdvalchange(self):
        self.valshow.setText(str(self.tb_thresholdVal.value()))
        self.Signal_OneParameter.emit(self.tb_thresholdVal.value(),self.tb_thresholdMax.value(),self.threshold_flag[self.com_box.currentText()])


