# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1215, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 581, 111))
        self.groupBox.setObjectName("groupBox")
        self.cmb_algorithm = QtWidgets.QComboBox(self.groupBox)
        self.cmb_algorithm.setGeometry(QtCore.QRect(10, 70, 441, 31))
        self.cmb_algorithm.setObjectName("cmb_algorithm")
        self.txt_PathShow = QtWidgets.QTextEdit(self.groupBox)
        self.txt_PathShow.setGeometry(QtCore.QRect(10, 20, 441, 31))
        self.txt_PathShow.setObjectName("txt_PathShow")
        self.btn_ReadPath = QtWidgets.QPushButton(self.groupBox)
        self.btn_ReadPath.setGeometry(QtCore.QRect(460, 20, 111, 31))
        self.btn_ReadPath.setObjectName("btn_ReadPath")
        self.label1 = QtWidgets.QLabel(self.groupBox)
        self.label1.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.label1.setObjectName("label1")
        self.btn_procressimg = QtWidgets.QPushButton(self.groupBox)
        self.btn_procressimg.setGeometry(QtCore.QRect(460, 70, 111, 31))
        self.btn_procressimg.setObjectName("btn_procressimg")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(610, 0, 581, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cmb_algorithm_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.cmb_algorithm_2.setGeometry(QtCore.QRect(10, 70, 441, 31))
        self.cmb_algorithm_2.setObjectName("cmb_algorithm_2")
        self.txt_PathShow_2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.txt_PathShow_2.setGeometry(QtCore.QRect(10, 20, 441, 31))
        self.txt_PathShow_2.setObjectName("txt_PathShow_2")
        self.btn_ReadPath_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_ReadPath_2.setGeometry(QtCore.QRect(460, 20, 111, 31))
        self.btn_ReadPath_2.setObjectName("btn_ReadPath_2")
        self.label1_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label1_2.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.label1_2.setObjectName("label1_2")
        self.btn_procressimg_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_procressimg_2.setGeometry(QtCore.QRect(460, 70, 111, 31))
        self.btn_procressimg_2.setObjectName("btn_procressimg_2")

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 120, 581, 511))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 579, 509))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.lab_showImg = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lab_showImg.setGeometry(QtCore.QRect(0, 0, 581, 511))
        self.lab_showImg.setObjectName("lab_showImg")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(610, 120, 581, 511))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 579, 509))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.lab_showImg_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lab_showImg_2.setGeometry(QtCore.QRect(0, 0, 581, 511))
        self.lab_showImg_2.setObjectName("lab_showImg_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1215, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txt_PathShow, self.btn_ReadPath)
        MainWindow.setTabOrder(self.btn_ReadPath, self.cmb_algorithm)
        MainWindow.setTabOrder(self.cmb_algorithm, self.txt_PathShow_2)
        MainWindow.setTabOrder(self.txt_PathShow_2, self.btn_ReadPath_2)
        MainWindow.setTabOrder(self.btn_ReadPath_2, self.cmb_algorithm_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setProperty("AAAAAA", _translate("MainWindow", "BBBBBBBBBBB"))
        self.groupBox.setTitle(_translate("MainWindow", "读取图片"))
        self.btn_ReadPath.setText(_translate("MainWindow", "加载图像"))
        self.label1.setText(_translate("MainWindow", "算法选择:"))
        self.btn_procressimg.setText(_translate("MainWindow", "处理"))
        self.groupBox_2.setTitle(_translate("MainWindow", "读取图片"))
        self.btn_ReadPath_2.setText(_translate("MainWindow", "加载图像"))
        self.label1_2.setText(_translate("MainWindow", "算法选择:"))
        self.btn_procressimg_2.setText(_translate("MainWindow", "处理"))
        self.lab_showImg.setText(_translate("MainWindow", "TextLabel"))
        self.lab_showImg_2.setText(_translate("MainWindow", "TextLabel"))
