# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(315, 131)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cb_Thresholdflag = QtWidgets.QComboBox(self.centralwidget)
        self.cb_Thresholdflag.setGeometry(QtCore.QRect(60, 0, 241, 22))
        self.cb_Thresholdflag.setObjectName("cb_Thresholdflag")
        self.tbar_ThresholdVal = QtWidgets.QSlider(self.centralwidget)
        self.tbar_ThresholdVal.setGeometry(QtCore.QRect(60, 30, 241, 22))
        self.tbar_ThresholdVal.setOrientation(QtCore.Qt.Horizontal)
        self.tbar_ThresholdVal.setObjectName("tbar_ThresholdVal")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 31, 16))
        self.label_2.setObjectName("label_2")
        self.tbar_ThresholdMax = QtWidgets.QSlider(self.centralwidget)
        self.tbar_ThresholdMax.setGeometry(QtCore.QRect(60, 60, 241, 22))
        self.tbar_ThresholdMax.setOrientation(QtCore.Qt.Horizontal)
        self.tbar_ThresholdMax.setObjectName("tbar_ThresholdMax")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 41, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 315, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Threshold"))
        self.cb_Thresholdflag.setWhatsThis(_translate("MainWindow", "Thresholdflag"))
        self.label.setText(_translate("MainWindow", "标志："))
        self.label_2.setText(_translate("MainWindow", "阈值："))
        self.label_3.setText(_translate("MainWindow", "最大值："))
